## Sample Sass Lint File
#########################
# Linter Options
files:
   ignore:
   - 'node_modules/**'
options:
  # Don't merge default rules
  merge-default-rules: true
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# Rule Configuration
rules:
  no-css-comments: 0
  pseudo-element: 0
  single-line-per-selector: 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations: 2
  no-warn: 2
  no-debug: 2
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 3
  property-sort-order:
    - 2
